#ifndef SEG_STRINGS
#define SEG_STRINGS
#include <inttypes.h>
struct seg_string{
    uint64_t length;
    uint64_t capacity;
    char* data;
};
struct seg_utf16_string{
    uint64_t length;
    uint64_t capacity;
    uint16_t* data;
};
struct seg_string_list{
    uint64_t length;
    uint64_t capacity;
    struct seg_string* data;
};
struct seg_utf16_string_list{
    uint64_t length;
    uint64_t capacity;
    struct seg_ms_string* data;
};
struct seg_string seg_empty_string(void);
struct seg_string seg_reserve_string(uint64_t);
void seg_increase_string_capacity(struct seg_string*,uint64_t);
void seg_add_char(struct seg_string*,char);
char seg_char_at(struct seg_string,uint64_t);
void seg_set_char(struct seg_string,uint64_t,char);
void seg_concatenate(struct seg_string*,struct seg_string);
void seg_concatenate_c_str(struct seg_string*,char*);
void seg_move_string(struct seg_string*,struct seg_string*);
void seg_clear_string(struct seg_string*);
/*Deprecated*/ void seg_display_string(struct seg_string);
char seg_pop_char(struct seg_string*);
char seg_remove_char(struct seg_string*,uint64_t);
char seg_delete_char(struct seg_string*,uint64_t);
char* seg_c_str(struct seg_string);
char seg_cmp_strings(struct seg_string,struct seg_string);
char seg_cmp_string_c_str(struct seg_string,char*);
uint64_t seg_uint_from_string(struct seg_string);
struct seg_string seg_string_from_uint(uint64_t);
struct seg_string seg_build_string(char*);
struct seg_string seg_copy_string(struct seg_string);
void seg_copy_string_into(struct seg_string*,struct seg_string);
/*Deprecated*/ uint64_t seg_string_size(struct seg_string);
/*Deprecated*/ uint64_t seg_string_cap(struct seg_string);
void seg_destroy_string(struct seg_string*);
struct seg_utf16_string seg_empty_utf16_string(void);
struct seg_utf16_string seg_reserve_utf16_string(uint64_t);
void seg_increase_utf16_string(struct seg_utf16_string*,uint64_t);
void seg_add_utf16_point(struct seg_utf16_string*,uint16_t);
uint16_t seg_utf16_point_at(struct seg_utf16_string,uint64_t);
void seg_set_utf16_point(struct seg_utf16_string,uint64_t,uint16_t);
void seg_utf16_concatenate(struct seg_utf16_string*,struct seg_utf16_string);
void seg_utf16_concatenate_utf16_str(struct seg_utf16_string*,uint16_t*);
void seg_move_utf16_string(struct seg_utf16_string*,struct seg_utf16_string*);
void seg_clear_utf16_string(struct seg_utf16_string*);
uint16_t seg_pop_utf16_point(struct seg_utf16_string*);
uint16_t seg_remove_utf16_point(struct seg_utf16_string*);
uint16_t seg_delete_utf16_point(struct seg_utf16_string*);
uint16_t* seg_utf16_str(struct seg_utf16_string);
char seg_cmp_utf16_strings(struct seg_utf16_string,struct seg_utf16_string);
char seg_cmp_utf16_string_utf16_str(struct seg_utf16_string,uint16_t*);
uint64_t seg_uint_from_utf16_string(struct seg_utf16_string);
struct seg_utf16_string seg_utf16_string_from_uint(uint64_t);
struct seg_utf16_string seg_build_utf16_string(uint16_t*);
struct seg_utf16_string seg_copy_utf16_string(struct seg_utf16_string);
void seg_copy_utf16_string_into(struct seg_utf16_string*,struct seg_utf16_string);
struct seg_utf16_string seg_into_utf16(struct seg_string);
struct seg_string seg_from_utf16(struct seg_utf16_string);
void seg_destroy_utf16_string(struct seg_utf16_string*);
struct seg_string_list seg_create_string_list(void);
struct seg_string_list seg_build_string_list(int,char**);
void seg_add_string(struct seg_string_list*,struct seg_string);
void seg_add_string_no_copy(struct seg_string_list*,struct seg_string);
struct seg_string seg_string_at(struct seg_string_list,uint64_t);
void seg_set_string(struct seg_string_list,uint64_t,struct seg_string);
void seg_set_string_data(struct seg_string_list,uint64_t,struct seg_string);
struct seg_string seg_pop_string(struct seg_string_list*);
struct seg_string seg_remove_string(struct seg_string_list*,uint64_t);
struct seg_string_list seg_split_string(struct seg_string,char);
struct seg_string seg_join_strings(struct seg_string_list,char);
struct seg_string seg_join_strings_raw(struct seg_string_list);
struct seg_string seg_join_strings_range(struct seg_string_list,char,uint64_t,uint64_t);
struct seg_string seg_join_strings_range_raw(struct seg_string_list,uint64_t,uint64_t);
void seg_prefix_strings(struct seg_string_list*,struct seg_string);
struct seg_string seg_prefix_and_join_strings(struct seg_string_list*,struct seg_string,char);
struct seg_string seg_prefix_and_join_strings_raw(struct seg_string_list*,struct seg_string);
void seg_prefix_strings_c_str(struct seg_string_list*,char*);
struct seg_string seg_prefix_c_str_and_join_strings(struct seg_string_list*,char*,char);
struct seg_string seg_prefix_c_str_and_join_strings_raw(struct seg_string_list*,char*);
uint64_t seg_string_list_size(struct seg_string_list);
uint64_t seg_string_list_cap(struct seg_string_list);
void seg_add_c_str(struct seg_string_list*,char*);
void seg_copy_string_into_index(struct seg_string_list*,uint64_t,struct seg_string);
void seg_destroy_string_list(struct seg_string_list*);
uint64_t seg_match_string(struct seg_string,struct seg_string_list);
struct seg_utf16_string_list seg_create_utf16_string_list(void);
struct seg_utf16_string_list seg_build_utf16_string_list(int,uint16_t**);
void seg_add_utf16_string(struct seg_utf16_string_list*,struct seg_utf16_string);
void seg_add_utf16_string_no_copy(struct seg_utf16_string_list*,struct seg_utf16_string);
struct seg_utf16_string seg_utf16_string_at(struct seg_utf16_string_list,uint64_t);
void seg_set_utf16_string(struct seg_utf16_string_list,uint64_t,struct seg_utf16_string);
void seg_set_utf16_string_data(struct seg_utf16_string_list,uint64_t,struct seg_utf16_string);
struct seg_utf16_string seg_pop_utf16_string(struct seg_utf16_string_list*);
struct seg_utf16_string seg_remove_utf16_string(struct seg_utf16_string_list*,uint64_t);
#endif